<?php

namespace App\Exceptions;

use Exception;

class UserHasBeenTakenException extends Exception
{
    protected $message = 'UsuÃ¡rio jÃ¡ existe!';

    public function render()
    {
        return response()->json([
            'error'=>class_basename($this),
            // 'message'=> 'email ou senha invÃ¡lido!'
            // 'message'=> $this->getMessage()
            'message'=> $this->getMessage()

        ], 400);

    }
}
